### ISSUE TITLE
吐槽一下 

### ISSUE THREAD

**Issue by shiwl0329** [smilelight/lightNLP#14]
![image](https://user-images.githubusercontent.com/13725297/99926334-51699280-2d7c-11eb-9676-4918639a38ba.png)
吐槽一下：这个line如果是以空格开头的，sc-ner模型都跑不起来。看来还是得找正规点的模型，坑有点多，本来提供一个数据就可以直接跑了，结果调试模型代码半天，太浪费时间了。。。

**Comment by smilelight** [comment]
抱歉抱歉，这个bug确实有点多。。。

**Comment by shiwl0329** [comment]
> 抱歉抱歉，这个bug确实有点多。。。

未来可期，优化一波，以后将会是一个超级棒的Git项目，哈哈

**Comment by smilelight** [comment]
哈哈，谢谢。这项目最开始是拿来练手的许多也都不咋懂，现在也好久没优化了，以后有时间我再改改。目前的话，使用起来应该会遇到不少问题。。。
