### ISSUE TITLE
测试的错误

### ISSUE THREAD

**Issue by Godlikemandyy** [smilelight/lightNLP#2]
您好：
使用你的代码测试了一下出了一下错误：ModuleNotFoundError: No module named 'lightnlp.sl.pos.utils'，请问这个错误是怎么导致的？
谢谢

**Comment by BUPTHYP** [comment]
同问 我也不知道这个怎么报错的

**Comment by smilelight** [comment]
忘了在utilsx文件夹内添加__init__.py文件，现在已修复～
