### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by kiwivk** [smilelight/lightNLP#5]
可以麻烦你提供一下数据集吗？或者数据集的链接

**Comment by smilelight** [comment]
你好，暂不提供，可以自己网上找找，或者去我的参考项目里找找；之后可能会整理一份。

**Comment by kiwivk** [comment]
很感谢你的回复，想请教一下你的模型框架是分散的吗？把很多模型整合了一下，分开单独训练？之间并没有什么关系？是这样的吗？

**Comment by smilelight** [comment]
是的，这些模型都是参考github上各任务开源实现后以一种比较统一的方式组织到一起，都分别对应于不同的任务和数据集，所以之间是相互独立的，互不影响。

**Comment by kiwivk** [comment]
好的，谢谢你

**Comment by smilelight** [comment]
：)，不客气
